apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /data-provider/(.+)
            backend:
              serviceName: data-provider-service
              servicePort: 8000
          - path: /consent-manager/(.+)
            backend:
              serviceName: consent-manager-service
              servicePort: 8000
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 3000
