apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: services-infrastructure
build:
  artifacts:
  - image: consent-manager/latest
    context: consent-manager
  - image: data-provider/latest
    context: data-provider
  - image: frontend/latest
    context: frontend
deploy:
  kubectl:
    manifests:
    - ingress.yaml
    - service-addresses-configmap.yaml
    - consent-manager/consent-manager-service.yaml
    - data-provider/data-provider-service.yaml
    - frontend/frontend-service.yaml
