ENVIRONMENT = 'ENV'


# Database related constants
DATABASE_CONFIG = 'DATABASE_CONFIG'
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_TYPE = 'DATABASE_TYPE'
DATABASE_TYPE = 'DATABASE_TYPE'
DATABASE_DIRECTORY_PATH = 'DATABASE_DIRECTORY_PATH'
DATABASE_HOST = 'DATABASE_HOST'
DATABASE_URL = 'DATABASE_URL'
DATABASE_USERNAME = 'DATABASE_USERNAME'
DATABASE_PASSWORD = 'DATABASE_PASSWORD'

# Models related constants
PROTECTED_KEYWORDS = [
    'marketplace', 'market', 'portfolio', 'projects', 'bot', 'bots'
]

MAX_LENGTH_SLUG = 24
MIN_LENGTH_SLUG = 4

MAX_LENGTH_PASSWORD = 125
MIN_LENGTH_PASSWORD = 4

MAX_LENGTH_FIRST_NAME = 35
MIN_LENGTH_FIRST_NAME = 1

MAX_LENGTH_LAST_NAME = 35
MIN_LENGTH_LAST_NAME = 1
