apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  selector:
    matchLabels:
      app: user-management
  replicas: 2
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management/latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: ENV
            value: "dev"
