ENVIRONMENT = 'ENV'
APP_SECRET_KEY = 'SECRET_KEY'
EMAIL_SECRET_KEY = 'EMAIL_SECRET_KEY'
EMAIL_SECRET_SALT = 'EMAIL_SECRET_SALT'
JWT_ACCESS_TOKEN_EXPIRES = 'JWT_ACCESS_TOKEN_EXPIRES'
TEMPORARY_STORAGE = 'TEMPORARY_STORAGE'
AWS_S3_ACCESS_KEY = 'AWS_S3_ACCESS_KEY'
AWS_S3_SECRET = 'AWS_S3_SECRET'
LOG_LEVEL = 'LOG_LEVEL'

# Database related constants
DATABASE_CONFIG = 'DATABASE_CONFIG'
DATABASE_NAME = 'DATABASE_NAME'
DATABASE_TYPE = 'DATABASE_TYPE'
DATABASE_DIRECTORY_PATH = 'DATABASE_DIRECTORY_PATH'
DATABASE_HOST = 'DATABASE_HOST'
DATABASE_URL = 'DATABASE_URL'
DATABASE_USERNAME = 'DATABASE_USERNAME'
DATABASE_PASSWORD = 'DATABASE_PASSWORD'


# Models related constants
PROTECTED_KEYWORDS = [
    'marketplace', 'market', 'portfolio', 'projects', 'bot', 'bots',
    'algorithm', 'profile'
]

MAX_LENGTH_SLUG = 24
MIN_LENGTH_SLUG = 4

MAX_LENGTH_PASSWORD = 125
MIN_LENGTH_PASSWORD = 4

MAX_LENGTH_FIRST_NAME = 35
MIN_LENGTH_FIRST_NAME = 1

MAX_LENGTH_LAST_NAME = 35
MIN_LENGTH_LAST_NAME = 1

MIN_LENGTH_COMMENT = 2
MAX_LENGTH_COMMENT = 400

MIN_LENGTH_TITLE = 4
MAX_LENGTH_TITLE = 48

MIN_LENGTH_SHORT_DESCRIPTION = 48
MAX_LENGTH_SHORT_DESCRIPTION = 200

MIN_LENGTH_DESCRIPTION = 48
MAX_LENGTH_DESCRIPTION = 2500

# Bot related constants
MIN_LENGTH_ALGORITHM_TITLE = 4
MAX_LENGTH_ALGORITHM_TITLE = 24

MAX_LENGTH_ALGORITHM_REVIEW = 400
MIN_LENGTH_ALGORITHM_REVIEW = 4

ALLOWED_PICTURE_FILE_EXTENSIONS = ['png', 'PNG', 'jpeg', 'jpg']

USER_MANAGER_SERVICE_ADDRESS = 'USER_MANAGER_SERVICE_ADDRESS'
ORGANIZATION_SERVICE_ADDRESS = 'ORGANIZATION_SERVICE_ADDRESS'

AWS_S3_IMAGES_BUCKET = 'AWS_S3_IMAGES_BUCKET'
AWS_S3_IMAGES_BUCKET_FOLDER = 'AWS_S3_IMAGES_BUCKET_FOLDER'

ALLOWED_IMAGE_FILE_EXTENSIONS = ['png', 'PNG', 'jpeg', 'jpg']
