openapi: 3.0.1
info:
  title: Policy Broker
  description: 'Policy Broker implementation based on the reference archicitecture'
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
- url: /

paths:
  '/selection':
    post:
      tags: 
        - Selection Services
      summary: Get a selection of consent managers that match the data category and intent of usage permissions and obligations
      operationId: requestSelection
      requestBody:
        $ref: '#/components/requestBodies/SelectionRequestBody'
      responses:
        '200':
          description: OK
  '/register':
    post:
      tags: 
        - Registration Services
      summary: Register as a consent manager at the policy broker
      operationId: register
      requestBody:
        $ref: '#/components/requestBodies/RegisterRequestBody'
      responses:
        '200':
          description: OK

components:
  schemas:
  
    DataPermission:
      type: object
      properties:
        attribute_id:
          type: string
        attribute_constraint:
          type: string
        data_category:
          type: string

    DataObligation:
      type: object
      properties:
        attribute_id:
          type: string
        attribute_constraint:
          type: string
        data_category:
          type: string
        

  requestBodies:
    
    SelectionRequestBody: 
      description: The intent of usage permissions and obligations
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              dataCategory:
                type: "string"
                example: "energy_usage"
              permissions:
                type: "array"
                items:
                  $ref: '#/components/schemas/DataPermission'
              obligations:
                type: "array"
                items:
                  $ref: '#/components/schemas/DataObligation'
            
    RegisterRequestBody:
      description: Registration of a consent manager
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              consent_manager:
                type: "string"
                example: "91ac9771-33d5-46e2-86e0-371636be3ac6"

    DataObligationBody:
      description: "The data obligation to be created"
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataObligation'

    RequestDataPolicyBody:
      description: "A policy request"
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              data_consumer_id:
                type: "string"
                format: UUID
              data_permissions:
                type: "array"
                items:
                  $ref: '#/components/schemas/DataPermission'
              data_obligations:
                type: "array"
                items:
                  $ref: '#/components/schemas/DataObligation'

  responses:
    
    DataPolicyResponse:
      description: Response of data policy
      content:
        application/xml:
          schema:
            type: string
            format: binary
    
    StoreDataPolicyResponse:
      description: Response of storing a data policy
      content:
        application/pdf:
          schema:
            type: string
            format: binary


    ListDataPermissionsResponse:
      description: List data permissions
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataPermission'

    ListDataObligationsResponse:
      description: List data obligations
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataObligation'

    CreateDataPermissionResponse:
      description: The created data permission
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataPermission'

    CreateDataObligationResponse:
      description: The created data obligation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataObligation'
    RequestDataPolicyResponse:
      description: A policy request response
      content:
        application/json:
          schema:
            type: object
            properties:
              policyId:
                type: string
                format: UUID
              status:
                type: string
              policy_catalogue:
                type: string
                format: UUID

    RequestDataPolicyStatusResponse:
      description: A policy request status
      content:
        application/json:
          schema:
            type: object
            properties:
              status:
                type: string
              policy_catalogue:
                type: string


