kind: "postgresql"
apiVersion: "acid.zalan.do/v1"

metadata:
  name: "acid-data-provider-cluster-one"
  namespace: "default"
  labels:
    team: acid

spec:
  teamId: "acid"
  postgresql:
    version: "12"
  numberOfInstances: 1
  volume:
    size: "10Gi"
  users:
    data-provider-user: []
    consent-manager-user: []
  databases:
    data_provider_db: data-provider-user
    consent_manager_db: consent-manager-user
  allowedSourceRanges:
    # IP ranges to access your cluster go here
  
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi