apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management
spec:
  selector:
    matchLabels:
      app: user-management
  replicas: 2
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: user-management/latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: ENV
            value: "dev"
          - name: DATABASE_PASSWORD
            valueFrom:
             secretKeyRef:
               name: data-provider-user.acid-services-cluster.credentials
               key: password
          - name: DATABASE_USERNAME
           valueFrom:
             secretKeyRef:
               name: data-provider-user.acid-services-cluster.credentials
               key: username
          - name: DATABASE_ENGINE
           value: "postgresql"
          - name: DATABASE_NAME
           value: "data_provider_db"
          - name: DATABASE_HOST
           value: "acid-services-cluster.default"