apiVersion: v1
kind: Service
metadata:
  name: data-provider-frontend-service
spec:
  selector:
    app: data-provider-frontend
  ports:
    - protocol: "TCP"
      port: 3000
      targetPort: 3000
  type: LoadBalancer