openapi: 3.0.1
info:
  title: Data Providers
  description: 'Data provider implementation based on the reference archicitecture'
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
- url: /

paths:
  '/data-owners':
    post:
      tags:
      - data owner services
      summary: Register a data owner
      operationId: createDataOwner
      requestBody:
        description: Data Owner object that needs to be added to the data provider
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DataOwner'
        required: true
      responses:
        201:
          $ref: '#/components/responses/DataOwnerCreateResponse'
      x-codegen-request-body-name: body
    get:
      tags:
      - data owner services
      summary: List data owners
      operationId: listDataOwners
      responses:
        200:
          $ref: '#/components/responses/ListDataOwnersResponse'
  '/{dataProdiderId}/data-sets':
    post:
      tags:
      - data set services
      summary: Register a data set
      parameters:
        - in: path
          name: dataProdiderId
          schema:
            type: string
          required: true
      operationId: createDataSet
      requestBody:
        $ref: '#/components/requestBodies/DataSetBody'
      responses:
        '201':
          $ref: '#/components/responses/DataSetCreateResponse'
      x-codegen-request-body-name: body
    get:
      tags:
      - data set services
      summary: List data sets
      parameters:
      - in: path
        name: dataProdiderId
        schema:
          type: string
        required: true
      operationId: listDataSet
      responses:
        200:
          $ref: '#/components/responses/ListDataSetsResponse'
  '/data-owners/{dataOwnerId}/data-sets':
    get:
        tags:
        - data set services
        summary: List data owner data sets
        parameters:
        - in: path
          name: dataOwnerId
          schema:
            type: string
          required: true
        operationId: listDataOwnerDataSets
        responses:
          200:
            $ref: '#/components/responses/ListDataSetsResponse'

  '/data-providers/':
    get:
      tags:
      - data providers services
      summary: List data providers
      operationId: listDataProviders
      responses:
        200:
          $ref: '#/components/responses/ListDataProviderResponse'
    post:
      tags:
        - data providers services
      summary: Register a data provider
      operationId: registerDataProvider
      requestBody:
        $ref: '#/components/requestBodies/DataProviderBody'
      responses:
          200:
            $ref: '#/components/responses/RegisterDataProviderResponse'

  '/data-owners/{dataOwnerId}/data-permissions':
    post:
      tags:
          - data permission services
      summary: Register a data permission
      parameters:
        - in: path
          name: dataOwnerId
          schema:
            type: string
          required: true
      operationId: registerDataOwnerPermission
      requestBody:
        $ref: '#/components/requestBodies/DataPermissionBody'
      responses:
          200:
            $ref: '#/components/responses/CreateDataPermissionResponse'

  '/data-owners/{dataOwnerId}/data-permissions/{dataCategory}':
    get:
      tags:
          - data permission services
      summary: List all data permissions for a data category
      parameters:
        - in: path
          name: dataOwnerId
          schema:
            type: string
          required: true
        - in: path
          name: dataCategory
          schema:
            type: string
          required: true
      operationId: listDataOwnerPermissions
      responses:
          200:
            $ref: '#/components/responses/ListDataPermissionsResponse'

  '/data-owners/{dataOwnerId}/data-obligations':
    post:
      tags:
          - data obligations services
      summary: Register a data permission
      parameters:
        - in: path
          name: dataOwnerId
          schema:
            type: string
          required: true
      operationId: registerDataOwnerObligation
      requestBody:
        $ref: '#/components/requestBodies/DataObligationBody'
      responses:
          200:
            $ref: '#/components/responses/CreateDataObligationResponse'
  '/data-owners/{dataOwnerId}/data-obligations/{dataCategory}':
    get:
      tags:
        - data obligations services
      summary: List all data obligations for a data category
      parameters:
        - in: path
          name: dataOwnerId
          schema:
            type: string
          required: true
        - in: path
          name: dataCategory
          schema:
            type: string
          required: true
      operationId: listDataOwnerObligations
      responses:
          200:
            $ref: '#/components/responses/ListDataObligationsResponse'
components:
  schemas:
    DataOwner:
      type: object
      properties:
        id:
          type: string
          format: uuid
    DataSet:
      type: object
      properties:
        id:
          type: string
          format: uuid
        data_category:
          type: string
          example: energy_usage_data
        data_owners:
          type: array
          items:
            $ref: '#/components/schemas/DataOwner'
    DataProvider:
      type: object
      properties:
        id:
          type: string
          format: uuid

    DataPermission:
      type: object
      properties:
        attribute_id:
          type: string
        attribute_constraint:
          type: string
        data_category:
          type: string

    DataObligation:
      type: object
      properties:
        attribute_id:
          type: string
        attribute_constraint:
          type: string
        data_category:
          type: string

  requestBodies:

    DataSetBody:
      description: The data set to be registered
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataSet'
    DataProviderBody:
      description: The provider to be registered
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataProvider'
    DataPermissionBody:
      description: The data permission to be created
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataPermission'

    DataObligationBody:
      description: "The data obligation to be created"
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataObligation'

  responses:

    # Default responses:
    DataOwnerCreateResponse:
      description: The created data owner
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataOwner'

    ListDataOwnersResponse:
      description: List of data owner objects
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataOwner'

    ListDataSetsResponse:
      description: List of data set objects
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataSet'

    DataSetCreateResponse:
      description: The created data set
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataSet'

    ListDataProviderResponse:
      description: List of data providers
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataProvider'

    ListDataPermissionsResponse:
      description: List data permissions
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataPermission'

    ListDataObligationsResponse:
      description: List data obligations
      content:
        application/json:
          schema:
            type: "array"
            items:
              $ref: '#/components/schemas/DataObligation'

    RegisterDataProviderResponse:
      description: The registered data provider
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataProvider'

    CreateDataPermissionResponse:
      description: The created data permission
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataPermission'

    CreateDataObligationResponse:
      description: The created data obligation
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/DataObligation'
